services:
  users_db:
    image: postgres:17-alpine
    container_name: usersDB_container
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DB=users_db
    volumes:
     - users_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"

  products_db:
    image: postgres:17-alpine
    container_name: productsDB_container
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DB=products_db
    volumes:
     - products_data:/var/lib/postgresql/data
    ports:
     - "5433:5432"

  user_service:
    build: ./Services/UserService/UserService.API
    container_name:
      user_service_container
    ports:
     - "8081:8080"
    depends_on:
     - users_db

  product_service:
    build: ./Services/ProductService/ProductService.API
    container_name:
      product_service_container
    ports:
     - "8082:8080"
    depends_on:
     - products_db

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
     - "8080:8080"
    depends_on:
     - products_db
     - users_db


volumes:
  users_data:
  products_data:  